# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/junhao/Desktop/octcoin/other_br/production/zilliqa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/junhao/Desktop/octcoin/other_br/production/zilliqa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/junhao/Desktop/octcoin/other_br/production/zilliqa/CMakeFiles /home/junhao/Desktop/octcoin/other_br/production/zilliqa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/junhao/Desktop/octcoin/other_br/production/zilliqa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) -f src/depends/common/CMakeFiles/Common.dir/build.make src/depends/common/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named json_spirit

# Build rule for target.
json_spirit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_spirit
.PHONY : json_spirit

# fast build rule for target.
json_spirit/fast:
	$(MAKE) -f src/depends/json_spirit/CMakeFiles/json_spirit.dir/build.make src/depends/json_spirit/CMakeFiles/json_spirit.dir/build
.PHONY : json_spirit/fast

#=============================================================================
# Target rules for targets named Overlay

# Build rule for target.
Overlay: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Overlay
.PHONY : Overlay

# fast build rule for target.
Overlay/fast:
	$(MAKE) -f src/depends/libDatabase/CMakeFiles/Overlay.dir/build.make src/depends/libDatabase/CMakeFiles/Overlay.dir/build
.PHONY : Overlay/fast

#=============================================================================
# Target rules for targets named Database

# Build rule for target.
Database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Database
.PHONY : Database

# fast build rule for target.
Database/fast:
	$(MAKE) -f src/depends/libDatabase/CMakeFiles/Database.dir/build.make src/depends/libDatabase/CMakeFiles/Database.dir/build
.PHONY : Database/fast

#=============================================================================
# Target rules for targets named ethash

# Build rule for target.
ethash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ethash
.PHONY : ethash

# fast build rule for target.
ethash/fast:
	$(MAKE) -f src/depends/libethash/CMakeFiles/ethash.dir/build.make src/depends/libethash/CMakeFiles/ethash.dir/build
.PHONY : ethash/fast

#=============================================================================
# Target rules for targets named Trie

# Build rule for target.
Trie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Trie
.PHONY : Trie

# fast build rule for target.
Trie/fast:
	$(MAKE) -f src/depends/libTrie/CMakeFiles/Trie.dir/build.make src/depends/libTrie/CMakeFiles/Trie.dir/build
.PHONY : Trie/fast

#=============================================================================
# Target rules for targets named minilzo

# Build rule for target.
minilzo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minilzo
.PHONY : minilzo

# fast build rule for target.
minilzo/fast:
	$(MAKE) -f src/depends/minilzo/CMakeFiles/minilzo.dir/build.make src/depends/minilzo/CMakeFiles/minilzo.dir/build
.PHONY : minilzo/fast

#=============================================================================
# Target rules for targets named Sha3

# Build rule for target.
Sha3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sha3
.PHONY : Sha3

# fast build rule for target.
Sha3/fast:
	$(MAKE) -f src/depends/Sha3/CMakeFiles/Sha3.dir/build.make src/depends/Sha3/CMakeFiles/Sha3.dir/build
.PHONY : Sha3/fast

#=============================================================================
# Target rules for targets named Consensus

# Build rule for target.
Consensus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Consensus
.PHONY : Consensus

# fast build rule for target.
Consensus/fast:
	$(MAKE) -f src/libConsensus/CMakeFiles/Consensus.dir/build.make src/libConsensus/CMakeFiles/Consensus.dir/build
.PHONY : Consensus/fast

#=============================================================================
# Target rules for targets named Crypto

# Build rule for target.
Crypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Crypto
.PHONY : Crypto

# fast build rule for target.
Crypto/fast:
	$(MAKE) -f src/libCrypto/CMakeFiles/Crypto.dir/build.make src/libCrypto/CMakeFiles/Crypto.dir/build
.PHONY : Crypto/fast

#=============================================================================
# Target rules for targets named AccountData

# Build rule for target.
AccountData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AccountData
.PHONY : AccountData

# fast build rule for target.
AccountData/fast:
	$(MAKE) -f src/libData/AccountData/CMakeFiles/AccountData.dir/build.make src/libData/AccountData/CMakeFiles/AccountData.dir/build
.PHONY : AccountData/fast

#=============================================================================
# Target rules for targets named Block

# Build rule for target.
Block: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Block
.PHONY : Block

# fast build rule for target.
Block/fast:
	$(MAKE) -f src/libData/BlockData/Block/CMakeFiles/Block.dir/build.make src/libData/BlockData/Block/CMakeFiles/Block.dir/build
.PHONY : Block/fast

#=============================================================================
# Target rules for targets named BlockHeader

# Build rule for target.
BlockHeader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockHeader
.PHONY : BlockHeader

# fast build rule for target.
BlockHeader/fast:
	$(MAKE) -f src/libData/BlockData/BlockHeader/CMakeFiles/BlockHeader.dir/build.make src/libData/BlockData/BlockHeader/CMakeFiles/BlockHeader.dir/build
.PHONY : BlockHeader/fast

#=============================================================================
# Target rules for targets named BlockChainData

# Build rule for target.
BlockChainData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockChainData
.PHONY : BlockChainData

# fast build rule for target.
BlockChainData/fast:
	$(MAKE) -f src/libData/BlockChainData/CMakeFiles/BlockChainData.dir/build.make src/libData/BlockChainData/CMakeFiles/BlockChainData.dir/build
.PHONY : BlockChainData/fast

#=============================================================================
# Target rules for targets named DirectoryService

# Build rule for target.
DirectoryService: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DirectoryService
.PHONY : DirectoryService

# fast build rule for target.
DirectoryService/fast:
	$(MAKE) -f src/libDirectoryService/CMakeFiles/DirectoryService.dir/build.make src/libDirectoryService/CMakeFiles/DirectoryService.dir/build
.PHONY : DirectoryService/fast

#=============================================================================
# Target rules for targets named Lookup

# Build rule for target.
Lookup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lookup
.PHONY : Lookup

# fast build rule for target.
Lookup/fast:
	$(MAKE) -f src/libLookup/CMakeFiles/Lookup.dir/build.make src/libLookup/CMakeFiles/Lookup.dir/build
.PHONY : Lookup/fast

#=============================================================================
# Target rules for targets named Mediator

# Build rule for target.
Mediator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mediator
.PHONY : Mediator

# fast build rule for target.
Mediator/fast:
	$(MAKE) -f src/libMediator/CMakeFiles/Mediator.dir/build.make src/libMediator/CMakeFiles/Mediator.dir/build
.PHONY : Mediator/fast

#=============================================================================
# Target rules for targets named Persistence

# Build rule for target.
Persistence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Persistence
.PHONY : Persistence

# fast build rule for target.
Persistence/fast:
	$(MAKE) -f src/libPersistence/CMakeFiles/Persistence.dir/build.make src/libPersistence/CMakeFiles/Persistence.dir/build
.PHONY : Persistence/fast

#=============================================================================
# Target rules for targets named POW

# Build rule for target.
POW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 POW
.PHONY : POW

# fast build rule for target.
POW/fast:
	$(MAKE) -f src/libPOW/CMakeFiles/POW.dir/build.make src/libPOW/CMakeFiles/POW.dir/build
.PHONY : POW/fast

#=============================================================================
# Target rules for targets named Network

# Build rule for target.
Network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Network
.PHONY : Network

# fast build rule for target.
Network/fast:
	$(MAKE) -f src/libNetwork/CMakeFiles/Network.dir/build.make src/libNetwork/CMakeFiles/Network.dir/build
.PHONY : Network/fast

#=============================================================================
# Target rules for targets named Node

# Build rule for target.
Node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Node
.PHONY : Node

# fast build rule for target.
Node/fast:
	$(MAKE) -f src/libNode/CMakeFiles/Node.dir/build.make src/libNode/CMakeFiles/Node.dir/build
.PHONY : Node/fast

#=============================================================================
# Target rules for targets named Utils

# Build rule for target.
Utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Utils
.PHONY : Utils

# fast build rule for target.
Utils/fast:
	$(MAKE) -f src/libUtils/CMakeFiles/Utils.dir/build.make src/libUtils/CMakeFiles/Utils.dir/build
.PHONY : Utils/fast

#=============================================================================
# Target rules for targets named Zilliqa

# Build rule for target.
Zilliqa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Zilliqa
.PHONY : Zilliqa

# fast build rule for target.
Zilliqa/fast:
	$(MAKE) -f src/libZilliqa/CMakeFiles/Zilliqa.dir/build.make src/libZilliqa/CMakeFiles/Zilliqa.dir/build
.PHONY : Zilliqa/fast

#=============================================================================
# Target rules for targets named Test_Sha3

# Build rule for target.
Test_Sha3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Sha3
.PHONY : Test_Sha3

# fast build rule for target.
Test_Sha3/fast:
	$(MAKE) -f tests/Crypto/CMakeFiles/Test_Sha3.dir/build.make tests/Crypto/CMakeFiles/Test_Sha3.dir/build
.PHONY : Test_Sha3/fast

#=============================================================================
# Target rules for targets named Test_Schnorr

# Build rule for target.
Test_Schnorr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Schnorr
.PHONY : Test_Schnorr

# fast build rule for target.
Test_Schnorr/fast:
	$(MAKE) -f tests/Crypto/CMakeFiles/Test_Schnorr.dir/build.make tests/Crypto/CMakeFiles/Test_Schnorr.dir/build
.PHONY : Test_Schnorr/fast

#=============================================================================
# Target rules for targets named Test_Sha3_fips

# Build rule for target.
Test_Sha3_fips: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Sha3_fips
.PHONY : Test_Sha3_fips

# fast build rule for target.
Test_Sha3_fips/fast:
	$(MAKE) -f tests/Crypto/CMakeFiles/Test_Sha3_fips.dir/build.make tests/Crypto/CMakeFiles/Test_Sha3_fips.dir/build
.PHONY : Test_Sha3_fips/fast

#=============================================================================
# Target rules for targets named Test_MultiSig

# Build rule for target.
Test_MultiSig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_MultiSig
.PHONY : Test_MultiSig

# fast build rule for target.
Test_MultiSig/fast:
	$(MAKE) -f tests/Crypto/CMakeFiles/Test_MultiSig.dir/build.make tests/Crypto/CMakeFiles/Test_MultiSig.dir/build
.PHONY : Test_MultiSig/fast

#=============================================================================
# Target rules for targets named Test_Account

# Build rule for target.
Test_Account: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Account
.PHONY : Test_Account

# fast build rule for target.
Test_Account/fast:
	$(MAKE) -f tests/Data/CMakeFiles/Test_Account.dir/build.make tests/Data/CMakeFiles/Test_Account.dir/build
.PHONY : Test_Account/fast

#=============================================================================
# Target rules for targets named Test_AccountStore

# Build rule for target.
Test_AccountStore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_AccountStore
.PHONY : Test_AccountStore

# fast build rule for target.
Test_AccountStore/fast:
	$(MAKE) -f tests/Data/CMakeFiles/Test_AccountStore.dir/build.make tests/Data/CMakeFiles/Test_AccountStore.dir/build
.PHONY : Test_AccountStore/fast

#=============================================================================
# Target rules for targets named Test_CircularArray

# Build rule for target.
Test_CircularArray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_CircularArray
.PHONY : Test_CircularArray

# fast build rule for target.
Test_CircularArray/fast:
	$(MAKE) -f tests/Data/CMakeFiles/Test_CircularArray.dir/build.make tests/Data/CMakeFiles/Test_CircularArray.dir/build
.PHONY : Test_CircularArray/fast

#=============================================================================
# Target rules for targets named Test_Transaction

# Build rule for target.
Test_Transaction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Transaction
.PHONY : Test_Transaction

# fast build rule for target.
Test_Transaction/fast:
	$(MAKE) -f tests/Data/CMakeFiles/Test_Transaction.dir/build.make tests/Data/CMakeFiles/Test_Transaction.dir/build
.PHONY : Test_Transaction/fast

#=============================================================================
# Target rules for targets named Test_LevelDB

# Build rule for target.
Test_LevelDB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_LevelDB
.PHONY : Test_LevelDB

# fast build rule for target.
Test_LevelDB/fast:
	$(MAKE) -f tests/depends/libDatabase/CMakeFiles/Test_LevelDB.dir/build.make tests/depends/libDatabase/CMakeFiles/Test_LevelDB.dir/build
.PHONY : Test_LevelDB/fast

#=============================================================================
# Target rules for targets named Test_LookupNodeForTxBlock

# Build rule for target.
Test_LookupNodeForTxBlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_LookupNodeForTxBlock
.PHONY : Test_LookupNodeForTxBlock

# fast build rule for target.
Test_LookupNodeForTxBlock/fast:
	$(MAKE) -f tests/Lookup/CMakeFiles/Test_LookupNodeForTxBlock.dir/build.make tests/Lookup/CMakeFiles/Test_LookupNodeForTxBlock.dir/build
.PHONY : Test_LookupNodeForTxBlock/fast

#=============================================================================
# Target rules for targets named Test_LookupNodeForDSBlock

# Build rule for target.
Test_LookupNodeForDSBlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_LookupNodeForDSBlock
.PHONY : Test_LookupNodeForDSBlock

# fast build rule for target.
Test_LookupNodeForDSBlock/fast:
	$(MAKE) -f tests/Lookup/CMakeFiles/Test_LookupNodeForDSBlock.dir/build.make tests/Lookup/CMakeFiles/Test_LookupNodeForDSBlock.dir/build
.PHONY : Test_LookupNodeForDSBlock/fast

#=============================================================================
# Target rules for targets named Test_PeerStore

# Build rule for target.
Test_PeerStore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_PeerStore
.PHONY : Test_PeerStore

# fast build rule for target.
Test_PeerStore/fast:
	$(MAKE) -f tests/Network/CMakeFiles/Test_PeerStore.dir/build.make tests/Network/CMakeFiles/Test_PeerStore.dir/build
.PHONY : Test_PeerStore/fast

#=============================================================================
# Target rules for targets named Test_DSPersistence

# Build rule for target.
Test_DSPersistence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_DSPersistence
.PHONY : Test_DSPersistence

# fast build rule for target.
Test_DSPersistence/fast:
	$(MAKE) -f tests/Persistence/CMakeFiles/Test_DSPersistence.dir/build.make tests/Persistence/CMakeFiles/Test_DSPersistence.dir/build
.PHONY : Test_DSPersistence/fast

#=============================================================================
# Target rules for targets named Test_TxPersistence

# Build rule for target.
Test_TxPersistence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_TxPersistence
.PHONY : Test_TxPersistence

# fast build rule for target.
Test_TxPersistence/fast:
	$(MAKE) -f tests/Persistence/CMakeFiles/Test_TxPersistence.dir/build.make tests/Persistence/CMakeFiles/Test_TxPersistence.dir/build
.PHONY : Test_TxPersistence/fast

#=============================================================================
# Target rules for targets named Test_TxBody

# Build rule for target.
Test_TxBody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_TxBody
.PHONY : Test_TxBody

# fast build rule for target.
Test_TxBody/fast:
	$(MAKE) -f tests/Persistence/CMakeFiles/Test_TxBody.dir/build.make tests/Persistence/CMakeFiles/Test_TxBody.dir/build
.PHONY : Test_TxBody/fast

#=============================================================================
# Target rules for targets named ReadBlock

# Build rule for target.
ReadBlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReadBlock
.PHONY : ReadBlock

# fast build rule for target.
ReadBlock/fast:
	$(MAKE) -f tests/Persistence/CMakeFiles/ReadBlock.dir/build.make tests/Persistence/CMakeFiles/ReadBlock.dir/build
.PHONY : ReadBlock/fast

#=============================================================================
# Target rules for targets named Test_Serializable

# Build rule for target.
Test_Serializable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Serializable
.PHONY : Test_Serializable

# fast build rule for target.
Test_Serializable/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_Serializable.dir/build.make tests/Utils/CMakeFiles/Test_Serializable.dir/build
.PHONY : Test_Serializable/fast

#=============================================================================
# Target rules for targets named Test_BoostBigNum

# Build rule for target.
Test_BoostBigNum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_BoostBigNum
.PHONY : Test_BoostBigNum

# fast build rule for target.
Test_BoostBigNum/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_BoostBigNum.dir/build.make tests/Utils/CMakeFiles/Test_BoostBigNum.dir/build
.PHONY : Test_BoostBigNum/fast

#=============================================================================
# Target rules for targets named Test_DetachedFunction

# Build rule for target.
Test_DetachedFunction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_DetachedFunction
.PHONY : Test_DetachedFunction

# fast build rule for target.
Test_DetachedFunction/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_DetachedFunction.dir/build.make tests/Utils/CMakeFiles/Test_DetachedFunction.dir/build
.PHONY : Test_DetachedFunction/fast

#=============================================================================
# Target rules for targets named Test_JoinableFunction

# Build rule for target.
Test_JoinableFunction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_JoinableFunction
.PHONY : Test_JoinableFunction

# fast build rule for target.
Test_JoinableFunction/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_JoinableFunction.dir/build.make tests/Utils/CMakeFiles/Test_JoinableFunction.dir/build
.PHONY : Test_JoinableFunction/fast

#=============================================================================
# Target rules for targets named Test_Logger1

# Build rule for target.
Test_Logger1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Logger1
.PHONY : Test_Logger1

# fast build rule for target.
Test_Logger1/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_Logger1.dir/build.make tests/Utils/CMakeFiles/Test_Logger1.dir/build
.PHONY : Test_Logger1/fast

#=============================================================================
# Target rules for targets named Test_Logger2

# Build rule for target.
Test_Logger2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Logger2
.PHONY : Test_Logger2

# fast build rule for target.
Test_Logger2/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_Logger2.dir/build.make tests/Utils/CMakeFiles/Test_Logger2.dir/build
.PHONY : Test_Logger2/fast

#=============================================================================
# Target rules for targets named Test_TimeLockedFunction

# Build rule for target.
Test_TimeLockedFunction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_TimeLockedFunction
.PHONY : Test_TimeLockedFunction

# fast build rule for target.
Test_TimeLockedFunction/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_TimeLockedFunction.dir/build.make tests/Utils/CMakeFiles/Test_TimeLockedFunction.dir/build
.PHONY : Test_TimeLockedFunction/fast

#=============================================================================
# Target rules for targets named Test_Logger3

# Build rule for target.
Test_Logger3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Logger3
.PHONY : Test_Logger3

# fast build rule for target.
Test_Logger3/fast:
	$(MAKE) -f tests/Utils/CMakeFiles/Test_Logger3.dir/build.make tests/Utils/CMakeFiles/Test_Logger3.dir/build
.PHONY : Test_Logger3/fast

#=============================================================================
# Target rules for targets named zilliqa

# Build rule for target.
zilliqa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zilliqa
.PHONY : zilliqa

# fast build rule for target.
zilliqa/fast:
	$(MAKE) -f tests/Zilliqa/CMakeFiles/zilliqa.dir/build.make tests/Zilliqa/CMakeFiles/zilliqa.dir/build
.PHONY : zilliqa/fast

#=============================================================================
# Target rules for targets named sendcmd

# Build rule for target.
sendcmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sendcmd
.PHONY : sendcmd

# fast build rule for target.
sendcmd/fast:
	$(MAKE) -f tests/Zilliqa/CMakeFiles/sendcmd.dir/build.make tests/Zilliqa/CMakeFiles/sendcmd.dir/build
.PHONY : sendcmd/fast

#=============================================================================
# Target rules for targets named genkeypair

# Build rule for target.
genkeypair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genkeypair
.PHONY : genkeypair

# fast build rule for target.
genkeypair/fast:
	$(MAKE) -f tests/Zilliqa/CMakeFiles/genkeypair.dir/build.make tests/Zilliqa/CMakeFiles/genkeypair.dir/build
.PHONY : genkeypair/fast

#=============================================================================
# Target rules for targets named sendtxn

# Build rule for target.
sendtxn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sendtxn
.PHONY : sendtxn

# fast build rule for target.
sendtxn/fast:
	$(MAKE) -f tests/Zilliqa/CMakeFiles/sendtxn.dir/build.make tests/Zilliqa/CMakeFiles/sendtxn.dir/build
.PHONY : sendtxn/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Common"
	@echo "... json_spirit"
	@echo "... Overlay"
	@echo "... Database"
	@echo "... ethash"
	@echo "... Trie"
	@echo "... minilzo"
	@echo "... Sha3"
	@echo "... Consensus"
	@echo "... Crypto"
	@echo "... AccountData"
	@echo "... Block"
	@echo "... BlockHeader"
	@echo "... BlockChainData"
	@echo "... DirectoryService"
	@echo "... Lookup"
	@echo "... Mediator"
	@echo "... Persistence"
	@echo "... POW"
	@echo "... Network"
	@echo "... Node"
	@echo "... Utils"
	@echo "... Zilliqa"
	@echo "... Test_Sha3"
	@echo "... Test_Schnorr"
	@echo "... Test_Sha3_fips"
	@echo "... Test_MultiSig"
	@echo "... Test_Account"
	@echo "... Test_AccountStore"
	@echo "... Test_CircularArray"
	@echo "... Test_Transaction"
	@echo "... Test_LevelDB"
	@echo "... Test_LookupNodeForTxBlock"
	@echo "... Test_LookupNodeForDSBlock"
	@echo "... Test_PeerStore"
	@echo "... Test_DSPersistence"
	@echo "... Test_TxPersistence"
	@echo "... Test_TxBody"
	@echo "... ReadBlock"
	@echo "... Test_Serializable"
	@echo "... Test_BoostBigNum"
	@echo "... Test_DetachedFunction"
	@echo "... Test_JoinableFunction"
	@echo "... Test_Logger1"
	@echo "... Test_Logger2"
	@echo "... Test_TimeLockedFunction"
	@echo "... Test_Logger3"
	@echo "... zilliqa"
	@echo "... sendcmd"
	@echo "... genkeypair"
	@echo "... sendtxn"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

