{
 "title": "Chain overview  v2",
 "description": "overview of the chain as a first approximation",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Forwarded TXs (P2P)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_finalblock_gauge{counter=\"ForwardedTx\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block height (TX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_mediator_gauge{counter=\"CurrentEpochNum\"}"
    }
   ]
  },
  {
   "title": "Current epoch number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_mediator_gauge{counter=\"CurrentEpochNum\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last block received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_finalblock_gauge{counter=\"LastBlockHeight\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last VC block height",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_finalblock_gauge{counter=\"LastVcBlockHeight\"}"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_threadpool_gauge{counter=\"Jobs\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}