{
 "title": "Consensus v2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "timed out making microblock!",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_finalblock_gauge{counter=\"TimedOutMicroblock\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DS is leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_directoryservice_gauge{counter=\"isLeader\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node state",
   "type": "graph",
   "description": "    0: POW_SUBMISSION\n    1: WAITING_DSBLOCK\n    2: MICROBLOCK_CONSENSUS_PREP,\n    3: MICROBLOCK_CONSENSUS,\n    4: WAITING_FINALBLOCK,\n    5: SYNC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_node_gauge {counter=\"NodeState\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DS state",
   "type": "graph",
   "description": "    POW_SUBMISSION = 0x00,\n    DSBLOCK_CONSENSUS_PREP,\n    DSBLOCK_CONSENSUS,\n    MICROBLOCK_SUBMISSION,\n    FINALBLOCK_CONSENSUS_PREP,\n    FINALBLOCK_CONSENSUS,\n    VIEWCHANGE_CONSENSUS_PREP,\n    VIEWCHANGE_CONSENSUS,\n    ERROR,\n    SYNC\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_directoryservice_gauge {counter=\"DSState\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DS committee size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_lookup_gauge {counter=\"DSCommitteeSize\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consensus leader state",
   "type": "graph",
   "description": "    INITIAL = 0x00,\n    ANNOUNCE_DONE,\n    COMMIT_DONE,\n    CHALLENGE_DONE,\n    RESPONSE_DONE,\n    COLLECTIVESIG_DONE,\n    FINALCOMMIT_DONE,\n    FINALCHALLENGE_DONE,\n    FINALRESPONSE_DONE,\n    DONE,\n    ERROR\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zilliqa_consensus_leader_gauge", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "missed microblock consensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_tx_finalblock_gauge{counter=\"MissedMicroblockConsensus\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}