{
 "title": "networking v2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "rumours:numTypes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"NumTypes\"}"
    }
   ]
  },
  {
   "title": "send jobs - send message to peer failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_sendjobs_gauge{counter=\"SendMessageToPeerFailed\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "rumours: lazypull",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"LazyPull\"}"
    }
   ]
  },
  {
   "title": "Send jobs - peer size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_sendjobs_gauge{counter=\"ActivePeersSize\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "rumours: lazypush",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"LazyPush\"}"
    }
   ]
  },
  {
   "title": "Event callback",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"EventCallback\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rumours: Forward",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"Forward\"}"
    }
   ]
  },
  {
   "title": "Event callback too few bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"EventCallbackTooFewBytes\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rumours: emptypull",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"EmptyPull\"}"
    }
   ]
  },
  {
   "title": "Gossip recvd forward.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"GossipReceivedForward\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rumours: emptypush",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"EmptyPush\"}"
    }
   ]
  },
  {
   "title": "Broadcasts recvd.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"BroadcastReceived\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rumours: pull",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"Pull\"}"
    }
   ]
  },
  {
   "title": "rumour message: push",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"Push\"}"
    }
   ]
  },
  {
   "title": "Rumours sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"RumoursSendMessage\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rumours Recvd",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_rumours_gauge{counter=\"RumoursReceived\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "message dispatch queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_msg_dispatch_queue_size{counter=\"QueueSize\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send Jobs - Send message to peer count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_sendjobs_gauge{counter=\"SendMessageToPeerCount\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gossip recvd.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"GossipReceived\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "new connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"NewConnections\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send Jobs - send message to peer syncronously",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_sendjobs_gauge{counter=\"SendMessageToPeerSyncCount\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Normal recvd.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"NormalReceived\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "server seed calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"EventCallbackServerSeed\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Event callback failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zilliqa_p2p_gauge{counter=\"EventCallbackFailure\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}