apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: devnet-config
  files:
  - constants.xml
  - extra_genesis.xml
  - genesis.xml
  - gentxn_init.py
  - init_py_opts.txt
  - init.py
  - launch_docker_p2pseed.sh
  - launch_docker.sh
  - launch_p2pseed.sh
  - launch.sh
  - logrotate-cron-hourly.sh
  - logrotate-s3.sh
  - logrotate.conf
  - logrotates3
  - isolated-server-accounts.json
