{
 "title": "Consensus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "DS state",
   "type": "timeseries",
   "description": "    POW_SUBMISSION = 0x00,\n    DSBLOCK_CONSENSUS_PREP,\n    DSBLOCK_CONSENSUS,\n    MICROBLOCK_SUBMISSION,\n    FINALBLOCK_CONSENSUS_PREP,\n    FINALBLOCK_CONSENSUS,\n    VIEWCHANGE_CONSENSUS_PREP,\n    VIEWCHANGE_CONSENSUS,\n    ERROR,\n    SYNC\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zilliqa_tx_lookup_gauge{counter=\"DSState\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DS is leader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "zilliqa_tx_lookup_gauge{counter=\"isLeader\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node state",
   "type": "timeseries",
   "description": "    0: POW_SUBMISSION\n    1: WAITING_DSBLOCK\n    2: MICROBLOCK_CONSENSUS_PREP,\n    3: MICROBLOCK_CONSENSUS,\n    4: WAITING_FINALBLOCK,\n    5: SYNC",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "zilliqa_node_gauge{counter=\"NodeState\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DS committee size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "zilliqa_tx_lookup_gauge{counter=\"DSCommitteeSize\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}