---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        env:
        - name: SERVICES
          value: s3
        #livenessProbe:
        #  httpGet:
        #    path: /_localstack/health
        #    port: 4566
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "awslocal s3 mb s3://devnet-bucket"]
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
  - protocol: TCP
    port: 4566
