apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../zilliqa/
nameSuffix: normal
commonLabels:
  type: normal


patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: devnet-
      labels:
        testnet: devnet
    spec:
      podManagementPolicy: Parallel
      replicas: 16