apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../zilliqa/
nameSuffix: dsguard
commonLabels:
  type: dsguard

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: devnet-
      labels:
        testnet: devnet
    spec:
      podManagementPolicy: Parallel
      replicas: 5