#include(ExternalProject)
#ExternalProject_Add(g3log
#    SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/depends/g3log
#    BUILD_COMMAND ""
#    INSTALL_COMMAND ""
#    CONFIGURE_COMMAND ""
#)
set(G3LOG_SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/depends/g3log)
set(G3LOG_BINARY_DIR ${CMAKE_BINARY_DIR}/src/depends/g3log)

file(MAKE_DIRECTORY ${G3LOG_BINARY_DIR})
execute_process(
    COMMAND ${CMAKE_COMMAND}
        -DUSE_DYNAMIC_LOGGING_LEVELS=ON
        -DG3_SHARED_LIB=OFF
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}
        -DADD_FATAL_EXAMPLE=OFF ${G3LOG_SOURCE_DIR}
    WORKING_DIRECTORY ${G3LOG_BINARY_DIR}
)
execute_process(
    COMMAND ${CMAKE_COMMAND} --build .
    WORKING_DIRECTORY ${G3LOG_BINARY_DIR}
)
execute_process(
    COMMAND ${CMAKE_COMMAND} --build . -- install
    WORKING_DIRECTORY ${G3LOG_BINARY_DIR}
)

list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})
list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}/lib/cmake/g3logger")
