name: Trivy scan

on:
  pull_request:
    branches:
    - staging
    - gamma
    - main

jobs:
  trivy-scan:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout scm
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'
        vuln-type: library
        exit-code: 0
